# Generated by Django 3.0 on 2019-12-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191210_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name': 'Пропорция', 'verbose_name_plural': 'Пропорции'},
        ),
    ]
