# Generated by Django 3.0 on 2020-01-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191210_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking',
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(default=15, verbose_name='время приготовления'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='level',
            field=models.IntegerField(default=1, verbose_name='сложность приготовления'),
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking', models.TextField(verbose_name='шаг приготовления')),
                ('image', models.ImageField(blank=True, upload_to='cooking_step_photos')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Recipe')),
            ],
            options={
                'verbose_name': 'Шаг приготовления',
                'verbose_name_plural': 'Шаги приготовления',
            },
        ),
    ]
